### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by samhk222** [romaricp/kit-starter-symfony-4-docker#1]
First of all, thank you very much for creating this image.

But i strongly recomend to run 

    mysql:
        image: mysql:5.7

instead of 

    mysql:
        image: mysql

because of the problems that may generate using the last version of mysql, like i did

**Comment by romaricp** [comment]
Thanks for your message @samhk222 

You right, you can force the version to use mysql5.7, but if you want still use the last version of mysql you can add this `command` option in your docker-compose : 

```
    mysql:
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password"
``` 

That's should work ;) 
I should take time to update this repo..

**Comment by romaricp** [comment]
it's fixed ! 👍 
https://github.com/romaricp/kit-starter-symfony-4-docker/pull/5
