### ISSUE TITLE
Lib zip

### ISSUE THREAD

**Issue by samhk222** [romaricp/kit-starter-symfony-4-docker#2]
Hi, it's me again :D 

Another nice feature it's to add a 

RUN docker-php-ext-install zip

at .docker/php/Dockerfile because the phpunit tests use that library (zip) and it's vittal to run your tests

**Comment by romaricp** [comment]
Hi @samhk222, that's a good idea ! 
Could you please create a PR for your features ? ;) 

Thx.

**Comment by patrick-mota** [comment]
If you add this line you will need zlib1g-dev too.

Here is my pull request fixing this problem:
https://github.com/romaricp/kit-starter-symfony-4-docker/pull/3

**Comment by romaricp** [comment]
Merged : https://github.com/romaricp/kit-starter-symfony-4-docker/pull/3 👍
