### ISSUE TITLE
mysql container doesnt start

### ISSUE THREAD

**Issue by BizBigs** [romaricp/kit-starter-symfony-4-docker#8]
Hi all,

First of all, really nice setup for symfony 4 with docker, i want tu use it to setup my env for my next project, and when i go with the `docker-compose up -d` then `docker-compose ps` here is what i get : 

     Name                   Command               State                Ports
-----------------------------------------------------------------------------------------
sf4_apache       /bin/sh -c apachectl  -DFO ...   Up       443/tcp, 0.0.0.0:80->80/tcp
sf4_maildev      bin/maildev --web 80 --smtp 25   Up       25/tcp, 0.0.0.0:8001->80/tcp
sf4_mysql        docker-entrypoint.sh --def ...   Exit 1
sf4_php          docker-php-entrypoint php-fpm    Up       9000/tcp
sf4_phpmyadmin   /run.sh supervisord -n -j  ...   Up       0.0.0.0:8080->80/tcp, 9000/tcp

sf4_mysql is not up. :(

Here is the logs : 

`$ docker logs sf4_mysql
Initializing database

2018-12-23T17:49:25.264385Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using this option as it' is deprecated and will be removed in a future release.

2018-12-23T17:49:25.269606Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.13) initializing of server in progress as process 27

2018-12-23T17:49:25.298851Z 0 [ERROR] [MY-010457] [Server] --initialize specified but the data directory has files in it. Aborting.

2018-12-23T17:49:25.305968Z 0 [ERROR] [MY-013236] [Server] Newly created data directory /var/lib/mysql/ is unusable. You can safely remove it.

2018-12-23T17:49:25.306052Z 0 [ERROR] [MY-010119] [Server] Aborting.`

Can anyone help me on this ? Maybe i've done something wrong ? I restarted all process even following your topic  (https://medium.com/@romaricp/the-perfect-kit-starter-for-a-symfony-4-project-with-docker-and-php-7-2-fda447b6bca1).

Thank you, Have a nice evening :)

**Comment by romaricp** [comment]
Hi, 
Are you on Mac OSX ? 
If yes, could you try to `rm -Rf` your containers and set the docker-compose.yml like this for mysql : 
```
        image: mysql
        command:
            - "--default-authentication-plugin=mysql_native_password"
            - "--lower_case_table_names=1"
```
Build and up all of this. ;)

**Comment by BizBigs** [comment]
Hi again,
I'm on Windows 10 pro,
I tried your solution tho, and it didn't work. :(

So i kept looking for an answer and i figured it out .. You can see it on my repo "drinkit" (i'm currently on my phone to answer you i'm sorry i don't have all the project in mind to tell you exactly what was my solution).

I found another problem with my solution tho, maybe you can help me out with this one (since i'm new to all this dockerise symfony 4 thing).

In the readme.md i explain the mysql instructions  i have to make inside the container to access phpmyadmin properly otherwise i get an access denied. I think this not good and it's not an optimised use of a mysql container. I'd prefer to not change the setup of a container once it's built and up. Maybe have you an alternative proposal for that issue ?

Anyway thank you for the answer, much appreciated. Have a nice holidays :)
